### ISSUE TITLE
ZMQMessage memory leak

### ISSUE THREAD

**Issue by mrazs-btl2** [jgcodes2020/CSZeroMQ#3]
Calling socket.ReceiveMsg causes a memory leak as messages aren't properly cleaned.
Libzmq's API says zmq_msg_close() should be called, so I tried calling it in ZMQMessage.cs:

```
        ~ZMQMessage()
        {
            fixed (zmq_msg_t* pMsg = &_msg)
            {
                zmq_msg_close(pMsg);
            }
        }
```

This did not fix the memory leak tho, any idea how to fix it?

**Comment by jgcodes2020** [comment]
I believe the proper way to do it would be to make `ZMQMessage` an `IDisposable` object, so that disposing it cleans up its memory. I can do a patch for this.

**Comment by jgcodes2020** [comment]
Should be fixed in the latest commit. ZMQMessage is IDisposable, letting you clean it up on the spot, but it *should* also be picked up by the GC if you don't dispose it.
